name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Instalar Node.js para utilizar htmlhint
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Instalar HTMLHint
      - name: Install HTMLHint
        run: npm install -g htmlhint

      # Ejecutar HTMLHint
      - name: Run HTMLHint
        run: htmlhint index.html nosotros.html producto.html

      # Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y etiquetar la imagen Docker
      - name: Build Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/freedom-motocross-store:latest
       
      # Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/freedom-motocross-store:latest
